### ISSUE TITLE
Using xsd schema validation with js2xmlparser

### ISSUE THREAD

**Issue by r3mus** [michaelkourlas/node-js2xmlparser#24]
I'm trying to replicate an XML API that outputs something like this:

```
<search xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://example.com/validate.xsd">
    <content></content>
</search>
```

How can I include this attribute in the root tag?

**Comment by michaelkourlas** [comment]
This should do what you want:

````
var obj = {
    "@": {
        "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "xsi:noNamespaceSchemaLocation": "http://example.com/validate.xsd"
    },
    "content": ""
};

console.log(js2xmlparser("search", obj));
````

**Comment by r3mus** [comment]
Zing! Nice one, thanks.

On February 23, 2015 at 12:52:39 PM, Michael Kourlas (notifications@github.com) wrote:

var obj = {
    "@": {
        "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "xsi:noNamespaceSchemaLocation": "http://example.com/validate.xsd"
    },
    "content": ""
};

console.log(js2xmlparser("search", obj));

**Comment by dejavxtrem** [comment]
How do I build a custom XML schema to work work with the parser?
