### ISSUE TITLE
Preserve Array Information

### ISSUE THREAD

**Issue by martinib77** [michaelkourlas/node-js2xmlparser#25]
When transforming an array to xml, the library repeats each array object with the same tag.
If the array has only one element, we lost the information about the original object, been an array.
Example
```json
    people: [{"name":"martin"}];
```
translates to:
 ```xml
   <people>
       <name>martin</name>
    </people>
```
Looking at the xml, we don't know that the original object was an array.

I did some changes to create an structure like this:
 ```xml
<arrayPeople>
     <people>
         <name>martin</name>
     </people>
 </arrayPeople>
 ```

It adds en element with "array" prefix.
What do you think of this?

Regards,

**Comment by martinib77** [comment]
Idea number 2,
add an "index" attribute for array elements,
so the result will be:
```xml
<people index="0">
   <name>martin</name>
</people>
```

If you agree i'll make a pull request with this change.

**Comment by michaelkourlas** [comment]
Regarding the first issue, js2xmlparser isn't really designed to include metadata about the JSON structure in the converted XML. If you need an array to be encapsulated by a special "array" tag, you should change your JSON structure to look like this:

````
{
    people: {
        person: [
            {
                name: "Martin"
            },
            {
                name: "Gregory"
            }
        ]
    }
}
````

The result will be the following:
````
<?xml version="1.0" encoding="UTF-8"?>
<person>
	<people>
		<person>
			<name>Martin</name>
		</person>
		<person>
			<name>Gregory</name>
		</person>
	</people>
</person>
````

**Comment by michaelkourlas** [comment]
Regarding the second issue, you can do the following:

````
{
    people: {
        person: [
            {
                "@": {
                    "index": 0
                },
                name: "Martin"
            },
            {
                "@": {
                    "index": 1
                },
                name: "Gregory"
            }
        ]
    }
}
````


````
<?xml version="1.0" encoding="UTF-8"?>
<person>
	<people>
		<person index="0">
			<name>Martin</name>
		</person>
		<person index="1">
			<name>Gregory</name>
		</person>
	</people>
</person>

**Comment by michaelkourlas** [comment]
I'm going to close this issue now, but feel free to re-open it if you have any further questions.
