### ISSUE TITLE
<?xml version="1.0" encoding="UTF-8"?> repeats for every line

### ISSUE THREAD

**Issue by herghost** [michaelkourlas/node-js2xmlparser#27]
Usage :
var js2xmlparser = require("js2xmlparser");
  var params = req.params.all();
        var json = params.id;

        var success = 1;

        var xml = js2xmlparser("row",json);
        console.log(xml);

result:

````
<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?>
<row>
	<user_id>429</user_id>
	<sku_id>1030589</sku_id>
	<qty>0</qty>
	<picklist_id>364720</picklist_id>
</row><row>
	<user_id>429</user_id>
	<sku_id>952656</sku_id>
	<qty>0</qty>
	<picklist_id>364720</picklist_id>
</row><row>
	<user_id>429</user_id>
	<sku_id>903790</sku_id>
	<qty>0</qty>
	<picklist_id>364720</picklist_id>
</row><row>
	<user_id>429</user_id>
	<sku_id>1029530</sku_id>
	<qty>0</qty>
	<picklist_id>364720</picklist_id>
</row><row>
	<user_id>429</user_id>
	<sku_id>998902</sku_id>
	<qty>0</qty>
	<picklist_id>364720</picklist_id>
</row>
````

**Comment by michaelkourlas** [comment]
XML documents cannot have more than one root element, so an array cannot be the root object that you pass into js2xmlparser (unless you're using the arrayMap functionality).

It's concerning that no error was thrown when you tried to do this, though.

**Comment by herghost** [comment]
Apologies, I found a similar issue in the closed issues section and closed this one.
In I parsed the data as JSON then the error appeared, however as I just sent it a String that contained the json data I guess it didn't know. It almost works though! I guess I could have just have done some regex on the xml and replaced the duplicate headers.
