### ISSUE TITLE
Parsing attributes issue

### ISSUE THREAD

**Issue by NetanelBasal** [michaelkourlas/node-js2xmlparser#28]
When i am trying to parse this to json:

```xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>
```

The output is:

```json
"urlset":{"$":{"xmlns":"http://www.sitemaps.org/schemas/sitemap/0.9"}
```

Then when i revert this to xml it is not how he was at the first place.

**Comment by michaelkourlas** [comment]
I'm not sure what tool you're using to go from XML to JSON, but to use js2xmlparser to convert the resulting JSON back to the same XML, you'll either need to:
* set the attributeString to "$", or
* change the "$" in your JSON to a "@", which is the default attribute string.
If "urlset" is your root element, then you'll need to pass that in separately as the root parameter and only pass in the "urlset" object as the data parameter.

Also, I think your JSON is missing a right close bracket.

**Comment by NetanelBasal** [comment]
I am sorry, i was confused from your plugin to xml to json plugin.
