### ISSUE TITLE
Added prefix option

### ISSUE THREAD

**Issue by ponyesteves** [michaelkourlas/node-js2xmlparser#41]
I'm working on a project that uses SOAP for exchanging data and I have the requirement of adding a prefix (namespace) in the tags 

I add this issue to keep track as @michaelkourlas  suggest. I've worked a solution but it can be merged directly. 

checkout PR #38

**Comment by chatumoh** [comment]
Is the support added to convert JSON to XML with namespace prefix in xml tag ?

**Comment by michaelkourlas** [comment]
I'm not sure there's a good way to implement this. A global prefix option wouldn't be flexible enough, given that examples of SOAP I've seen online have different prefixes in different parts of the document.

There are other ways to do this, but I think it would be easiest to just add the prefix to each object key manually.

**Comment by michaelkourlas** [comment]
In addition, if you can't change the keys, you can use the `aliasString` functionality instead for the same effect.

**Comment by davidhardin** [comment]
I'm having trouble accessing the alias string properties in my javascript code.

For example if I have 

"IntegerAttribute": [
                    {
                    "@" : {
                    "name": "ID",
                    "xmlns:ns2": "http://www.website.com/"
                    },
                      
                      "integer":{
                        "=":"ns2:integer",
                        "#":'1'
                      } 
                   }
]

Node throws an error when I try to access those @,#, and = properties. 

I need to read and write to them.

Can you suggest a solution? Thank you for this package!

**Comment by michaelkourlas** [comment]
> Node throws an error when I try to access those @,#, and = properties.

Can you clarify what you mean by this?

**Comment by davidhardin** [comment]
> > Node throws an error when I try to access those @,#, and = properties.
> 
> 
> 
> Can you clarify what you mean by this?

Hi. You can disregard. I was trying to reference those string aliases like #, @, and =. So, if I had an inline element called "name", I may try to set its value by using root.@.name = "myvalue". Node doesn't allow you to use that character as a property. I got around that by naming the @ property something else, "InlineElement", then replacing it with the @ character using stringify, split, join right before I converted it into xml, using js2xmlparser.parse.

Sorry, I'm new to node js. Again, I appreciate you creating this package. It was a lifesaver for me!

**Comment by michaelkourlas** [comment]
You can also access properties with those names directly using this syntax: `root["@"].name`

**Comment by davidhardin** [comment]
> You can also access properties with those names directly using this syntax: `root["@"].name`

Oh wow! Ok, that's much better! I'll try that.
