### ISSUE TITLE
HTML Entities ">" not convert to "&gt;"

### ISSUE THREAD

**Issue by noppadet008** [michaelkourlas/node-js2xmlparser#44]
I have use your convertor but some reserve char is not convert  HTML entities  please let some check
thank you ^^

this example some output what I got

`<Node Name="xxxxx" Type="Connection" Descr="&lt;tba>" Icon="mRemote" Panel="General" Domain="" Password="" ...`

**Comment by michaelkourlas** [comment]
Isn't the '>' character [valid in attribute names](https://www.w3.org/TR/xml/#NT-AttValue)?

**Comment by dedric** [comment]
Hi, 

I am seeing the same issue. I get the following

`<LongDescription>Experience our collection in the comfort of a Signature Store.&lt;ul>&lt;li>style: 1339-031T&lt;/li>&lt;li>eco-friendly hardwood frame&lt;/li>&lt;li>eco-friendly high-density, high-resiliency cushioning&lt;/li>&lt;li>seat: woven webbing, back: rigid sheet webbing&lt;/li>&lt;li>made in the USA&lt;/li>&lt;li>fabric info: linen colored basketweave, 38% linen, 32% rayon, 15% cotton, 15% polyester&lt;/li>&lt;li>finish: java&lt;/li>&lt;/ul></LongDescription>`

**Comment by noppadet008** [comment]
thank you for reply
it's not only in attribute it affect in text element in the same problem
input
```
    "address": {
        "streetAddress": "3212 22nd St><><><><<><><",
    },
```

output
```
<address type='home'>
<streetAddress>3212 22nd St>&lt;>&lt;>&lt;>&lt;&lt;>&lt;>&lt;</streetAddress>
</address>
```
has any solution?

**Comment by michaelkourlas** [comment]
I'm not really clear why this is an issue. In general, unlike '<' and '&', the '>' character doesn't have to be escaped in XML. According to [the spec](https://www.w3.org/TR/REC-xml/), the only time it has to be escaped is when it is part of the string "]]>":

> The ampersand character (&) and the left angle bracket (<) must not appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. If they are needed elsewhere, they must be escaped using either numeric character references or the strings " &amp; " and " &lt; " respectively. **The right angle bracket (>) may be represented using the string " &gt; ", and must, for compatibility, be escaped using either " &gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a CDATA section.**

I don't think js2xmlparser currently does that, actually, so *that* is a bug, but the fact remains that '>' doesn't need to be escaped in general.

**Comment by noppadet008** [comment]
Oh I've solve my problem, Frist I've found error form import file xml which generate form this library, I think cause  ">" invalid char . But actually problem is miss attribute when generate property undefined value.  I've workaround with added default value to prevent undefined case.
thank you for active reply ^^
