### ISSUE TITLE
Handling nulls

### ISSUE THREAD

**Issue by gilly3** [michaelkourlas/node-js2xmlparser#46]
It's impossible to determine whether a value is null or contains the string `"null"`.  Rather than turning a null into a string, I would expect a self-closing tag:

For the following example:

```javascript
require("js2xmlparser").parse("obj", { emptyVal: "", nullVal: null, stringVal: "null" })
```

The actual output is:

```xml
<?xml version='1.0'?>
<obj>
    <emptyVal></emptyVal>
    <nullVal>null</nullVal>
    <stringVal>null</stringVal>
</obj>
```

The desired output is:

```xml
<?xml version='1.0'?>
<obj>
    <emptyVal></emptyVal>
    <nullVal />
    <stringVal>null</stringVal>
</obj>
```

**Comment by michaelkourlas** [comment]
It looks like `<x></x>` and `<x/>` are [semantically equivalent](https://www.w3.org/TR/xml/#sec-starttags) in XML; they are both considered empty elements:

> The representation of an empty element is either a start-tag immediately followed by an end-tag, or an empty-element tag.

As such, if I went with your proposed solution, you'd end up with a similar ambiguity between `null` and empty strings -- they would both become empty elements.

Have you considered using the `typeHandlers` option to map `null` to an output value of your choice?

**Comment by gilly3** [comment]
I hadn't considered using `typeHandlers`.  At least I hadn't looked at that option closely enough to realize it might be what I was looking for.  So, if I wanted to covert `null` to empty string, would this options object do that?

```javascript
{
    typeHandlers: {
        "[object Null]": function (value) {
            return "";
        }
    }
}
```

**Comment by michaelkourlas** [comment]
Yes, that looks like it should do the job.

**Comment by adamdry** [comment]
For anyone that's interested here's my working example in TypeScript, which also includes a typeHandler for `undefined`:
```
        const contractXml: string = js2xmlparser.parse('Contract', ersContract, {
            typeHandlers: {
                '[object Null]': (value: any): string => {
                    return ''
                },
                '[object Undefined]': (value: any): string => {
                    return ''
                }
            }
        })
```

**Comment by milen-dobrinov** [comment]
How can I skip the creation of an xml element if the value is undefined? What should I return in the typeHandlers function?

**Comment by michaelkourlas** [comment]
See the documentation:

> If one of these functions returns the sole instance of Absent, then the value will be suppressed from the XML output altogether.
