### ISSUE TITLE
Change shrinkwrap to support private repos

### ISSUE THREAD

**Issue by danielkwinsor** [michaelkourlas/node-js2xmlparser#48]
Hi,

I'm not able to install this module behind my corporate proxy.  What I did was publish both this and xmlcreate to our private nexus, with an updated shrinkwrap that points to our own nexus.  But one other solution is to remove the `resolved` element entirely so that the npm client decides where to get it.

See also
https://support.sonatype.com/hc/en-us/articles/213465048-Why-does-npm-client-need-access-to-URLs-other-than-my-private-registry-
and 
https://github.com/npm/npm/issues/6444
and 
https://github.com/npm/npm/issues/3581#issuecomment-58610799

**Comment by michaelkourlas** [comment]
My research indicates that libraries generally don't use npm shrinkwrap anyways, so I'll probably just remove it in the next release. Thanks for bringing this to my attention.

**Comment by gilly3** [comment]
I'm hitting the same issue, and trying to decide whether to use v3.0.0 or if I will have to fork v2.0.2.  What is the breaking change from v2.0.2 to v3.0.0 that warranted the major version bump?

**Comment by michaelkourlas** [comment]
@gilly3: The package source was re-written for TypeScript 2.0, which included some backwards-incompatible features like the use of `null` and `undefined` in types.
