### ISSUE TITLE
Array map feature

### ISSUE THREAD

**Issue by Fabriciu** [michaelkourlas/node-js2xmlparser#49]
Hi,

I'm trying the array map feature, but it's not working:

---
Code:

var data = {
    "firstName": "John",
    "lastName": "Smith",
    "nicknames": [
        "Johnny", 
        "Jon", 
        "Jack"
    ]
}

var options = {
    arrayMap: {
        nicknames: "name"
    }
};

console.log(js2xmlparser.parse("person", data, options));

------
Output:

`<?xml version='1.0'?>
<person>
    <firstName>John</firstName>
    <lastName>Smith</lastName>
    <nicknames>Johnny</nicknames>
    <nicknames>Jon</nicknames>
    <nicknames>Jack</nicknames>
</person>`

**Comment by michaelkourlas** [comment]
The array map feature has been renamed to `wrapHandlers`. Please see [the documentation](http://www.kourlas.com/node-js2xmlparser/docs/2.0.2/interfaces/ioptions.html#wraphandlers) for more details.

**Comment by Fabriciu** [comment]
Thank you!
