### ISSUE TITLE
Wrapping Arrays

### ISSUE THREAD

**Issue by oprogfrogo** [michaelkourlas/node-js2xmlparser#51]
Using your package, how do I wrap an array so that this:

`items: [ '1', '2', '3', '4' ]`

becomes this:

```
<items type="array">
    <item>1</item>
    <item>2</item>
    <item>3</item>
    <item>4</item>
  </items>
```

**Comment by davidjr** [comment]
I have a similar question pertaining to arrayWrapping, here are the details:
let ebsXmlOptions = {
    wrapArray: {
        enabled: true
    },
    declaration: {
        include: true,
        encoding: "UTF-8",
        version: "1.0"
    },
    format: {
        doubleQuotes: true,
        indent: "\t",
        newline: "\r\n",
        pretty: true
    }
};

JSON (snippet, partial):
{
    "bof:LineItemList": [{
            "LineNum": "1",
            "OfferCode": "US-CLUB-USD",
            "ItemNumber": "MD21DBOD2101",
            "OriginalPrice": "26.96",
            "RetailPrice": "26.96",
            "Qty": "1",
            "UOM": "EA",
            "HDTriggerFlag": "1",
            "ItemPrice": "26.96",
            "ItemPaymentPlanCode": "1 Pay"
        },
        {
            "LineNum": "2",
            "OfferCode": "US-CLUB-USD",
            "ItemNumber": "MD21DBOD2102",
            "OriginalPrice": "13.46",
            "RetailPrice": "13.46",
            "Qty": "1",
            "UOM": "EA",
            "HDTriggerFlag": "1",
            "ItemPrice": "13.46",
            "ItemPaymentPlanCode": "1 Pay"
        }
    ]
}

Generated XML:
<bof:LineItemList>
    <bof:LineItem>
        <bof:LineNum>1</bof:LineNum>
        <bof:OfferCode>US-CLUB-USD</bof:OfferCode>
        <bof:ItemNumber>MD21DBOD2101</bof:ItemNumber>
        <bof:OriginalPrice>26.96</bof:OriginalPrice>
        <bof:RetailPrice>26.96</bof:RetailPrice>
        <bof:Qty>1</bof:Qty>
        <bof:UOM>EA</bof:UOM>
        <bof:HDTriggerFlag>1</bof:HDTriggerFlag>
        <bof:ItemPrice>26.96</bof:ItemPrice>
        <bof:ItemPaymentPlanCode>1 Pay</bof:ItemPaymentPlanCode>
    </bof:LineItem>
</bof:LineItemList>
<bof:LineItemList>
    <bof:LineItem>
        <bof:LineNum>2</bof:LineNum>
        <bof:OfferCode>US-CLUB-USD</bof:OfferCode>
        <bof:ItemNumber>MD21DBOD2102</bof:ItemNumber>
        <bof:OriginalPrice>13.46</bof:OriginalPrice>
        <bof:RetailPrice>13.46</bof:RetailPrice>
        <bof:Qty>1</bof:Qty>
        <bof:UOM>EA</bof:UOM>
        <bof:HDTriggerFlag>1</bof:HDTriggerFlag>
        <bof:ItemPrice>13.46</bof:ItemPrice>
        <bof:ItemPaymentPlanCode>1 Pay</bof:ItemPaymentPlanCode>
    </bof:LineItem>
</bof:LineItemList>

Desired XML:
<bof:LineItemList>
    <bof:LineItem>
        <bof:LineNum>1</bof:LineNum>
        <bof:OfferCode>US-CLUB-USD</bof:OfferCode>
        <bof:ItemNumber>MD21DBOD2101</bof:ItemNumber>
        <bof:OriginalPrice>26.96</bof:OriginalPrice>
        <bof:RetailPrice>26.96</bof:RetailPrice>
        <bof:Qty>1</bof:Qty>
        <bof:UOM>EA</bof:UOM>
        <bof:HDTriggerFlag>1</bof:HDTriggerFlag>
        <bof:ItemPrice>26.96</bof:ItemPrice>
        <bof:ItemPaymentPlanCode>1 Pay</bof:ItemPaymentPlanCode>
    </bof:LineItem>
    <bof:LineItem>
        <bof:LineNum>2</bof:LineNum>
        <bof:OfferCode>US-CLUB-USD</bof:OfferCode>
        <bof:ItemNumber>MD21DBOD2102</bof:ItemNumber>
        <bof:OriginalPrice>13.46</bof:OriginalPrice>
        <bof:RetailPrice>13.46</bof:RetailPrice>
        <bof:Qty>1</bof:Qty>
        <bof:UOM>EA</bof:UOM>
        <bof:HDTriggerFlag>1</bof:HDTriggerFlag>
        <bof:ItemPrice>13.46</bof:ItemPrice>
        <bof:ItemPaymentPlanCode>1 Pay</bof:ItemPaymentPlanCode>
    </bof:LineItem>
</bof:LineItemList>

**Comment by michaelkourlas** [comment]
@oprogfrogo The following object should produce the desired output
````javascript
var obj = {
    items: {
        "@": {
            type: "array"
        },
        "item": ["1", "2", "3", "4"]
    }
}
````
