### ISSUE TITLE
Ignore field with undefined or null value

### ISSUE THREAD

**Issue by marchah** [michaelkourlas/node-js2xmlparser#52]
Hi,

I'm doing the migration from `1.0.0` to `3.0.0`, in the old version when i field value was `undefined` or `null` it wasn't add to the xml string, how can i reproduce this in the new version.

Thanks

**Comment by michaelkourlas** [comment]
There's currently no way to do this, but I plan to add a feature that lets you specify certain values which should be suppressed on output.

**Comment by marchah** [comment]
@michaelkourlas Thank you for you answer.
Please let me know when you implement this feature.

**Comment by michaelkourlas** [comment]
This will be present in the next release. It'll be implemented using the existing typeHandlers functionality -- if you return a special value, objects with that type will be suppressed from the output.
