### ISSUE TITLE
Provide example for mixed content

### ISSUE THREAD

**Issue by raffazizzi** [michaelkourlas/node-js2xmlparser#53]
Could you provide an example (and/or test) of how mixed content should be represented? 

For example:

```xml
<el1>text1<el2>text2</el2>text3</el1>
```

**Comment by michaelkourlas** [comment]
The following object should produce the desired output:
````javascript
{
    el1: {
        "#1": "text1",
        el2: "text2",
        "#2": "text3"
    }
}
````

I believe example 5 already demonstrates this feature (multiple value entries).
