### ISSUE TITLE
Self-closing tag

### ISSUE THREAD

**Issue by ybrodsky** [michaelkourlas/node-js2xmlparser#54]
I don't seem to find anywhere how to create a self closing tag.

Desire:
```
  <One />
  <Two/>
  <Three>Some data</Three>
```

Json:
```
  {
    ???
    Three: 'Some Data'
  }
```

**Comment by jeremija** [comment]
You can use `parse('test', { one: {}, two: {}, three: 'Some data})`. Unfortunately this doesn't work with empty arrays:

```javascript
$ node

> xml = require('js2xmlparser')
{ parse: [Function: parse] }

> xml.parse('test', { one: {}, two: {}, three: 'Some data' })
'<?xml version=\'1.0\'?>\n<test>\n    <one/>\n    <two/>\n    <three>Some data</three>\n</test>'

> xml.parse('test', { one: [], two: [], three: 'Some data' })
'<?xml version=\'1.0\'?>\n<test>\n    <three>Some data</three>\n</test>'
```

**Comment by michaelkourlas** [comment]
Per [the XML spec](https://www.w3.org/TR/REC-xml/#NT-EmptyElemTag), empty-element tags should be preferred to standard tags that are simply empty.

Accordingly, I'll change the behaviour in a future (major) version and add an option to restore the old behaviour.

**Comment by michaelkourlas** [comment]
This will be configurable in the next release, which should be out shortly.
