### ISSUE TITLE
Can add envelop for generated xml, Please help me to do. 

### ISSUE THREAD

**Issue by khajaamin** [michaelkourlas/node-js2xmlparser#55]
Using this  lib I did  generated  xml 

I wan to add 

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <SOAP-ENV:Body>

this at beginning and 

 </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

at End. 

Please help.

**Comment by michaelkourlas** [comment]
I'm not sure I understand what you're asking. Can't you add the soap information to the object you're converting, or manually add it to the XML after converting?

**Comment by ziplokk1** [comment]
#71 Should fix what you're asking for.

**Comment by michaelkourlas** [comment]
Assuming attributes in the root element is what you're asking for, js2xmlparser already supports this:

```
> js2xmlparser.parse("root", {"@": {"abc": "def"}})
'<?xml version=\'1.0\'?>\n<root abc=\'def\'/>'
```
