### ISSUE TITLE
Attributes in root element

### ISSUE THREAD

**Issue by kkoteeswaran** [michaelkourlas/node-js2xmlparser#58]
I would like to build a XML request that looks like this:

```
<?xml version='1.0'?>
<person type="owner">
    <firstName>John</firstName>
    <lastName>Smith</lastName>
</person>
```
with attribute `type="owner"` in the root element. Is there a way to do that?

**Comment by dsych** [comment]
Based on [this](https://github.com/michaelkourlas/node-js2xmlparser/blob/master/examples/example.js#L42) example you can just say:
```js
let person = {
    "@":{
        "type": "owner"
     },
    "firstName": "John", 
    "lastName": "Smith"
}

console.log(js2xmlparser.parse("person", person));
```

**Comment by andresjuarez** [comment]
Excellent I had the same doubt! Thanks @dsych you are the man. I would close this issue

**Comment by kkoteeswaran** [comment]
Thank you!
