### ISSUE TITLE
Tags duplicating

### ISSUE THREAD

**Issue by omkartin** [michaelkourlas/node-js2xmlparser#59]
Hello @michaelkourlas ,

I am sending a json object like this:

[ { Vehicle: { Specifications: [Object] } },
  { Vehicle: { Specifications: [Object] } } ]

And I am doing js2xmlparse as follows

`js2xmlparser.parse("Inventory", req.body)`

`<?xml version='1.0'?>
<Inventory>
    <Inventory>
        <Vehicle>
            <Specifications>
                <Make>GMC</Make>
                <Model>ACADIA</Model>
                <Style>SLT-1 4DR SUV</Style>
                <Doors>4</Doors>
                <Cylinders>6</Cylinders>
                <Transmission>A</Transmission>
                <ExteriorColor>BROWN</ExteriorColor>
                <InteriorColor>BROWN</InteriorColor>
                <Engine></Engine>
            </Specifications>
        </Vehicle>
    </Inventory>
    <Inventory>
        <Vehicle>
            <Specifications>
                <Make>GMC</Make>
                <Model>ACADIA</Model>
                <Style>SLT-1 4DR SUV</Style>
                <Doors>4</Doors>
                <Cylinders>6</Cylinders>
                <Transmission>A</Transmission>
                <ExteriorColor>BROWN</ExteriorColor>
                <InteriorColor>BROWN</InteriorColor>
                <Engine></Engine>
            </Specifications>
        </Vehicle>
    </Inventory>
</Inventory>`

The inventory is added again inside. I am expecting this

`<?xml version='1.0'?>
<Inventory>
        <Vehicle>
            <Specifications>
                <Make>GMC</Make>
                <Model>ACADIA</Model>
                <Style>SLT-1 4DR SUV</Style>
                <Doors>4</Doors>
                <Cylinders>6</Cylinders>
                <Transmission>A</Transmission>
                <ExteriorColor>BROWN</ExteriorColor>
                <InteriorColor>BROWN</InteriorColor>
                <Engine></Engine>
            </Specifications>
        </Vehicle>
        <Vehicle>
            <Specifications>
                <Make>GMC</Make>
                <Model>ACADIA</Model>
                <Style>SLT-1 4DR SUV</Style>
                <Doors>4</Doors>
                <Cylinders>6</Cylinders>
                <Transmission>A</Transmission>
                <ExteriorColor>BROWN</ExteriorColor>
                <InteriorColor>BROWN</InteriorColor>
                <Engine></Engine>
            </Specifications>
        </Vehicle>
</Inventory>`

How can I achieve this ??

**Comment by michaelkourlas** [comment]
You're passing in an array, which means that js2xmlparser thinks you want to wrap the array elements in the root tag.

You need to pass in an object instead. Try:
```
{
  Vehicle: [
    { Specifications: [Object] },
    { Specifications: [Object] }
  ]
}
```
and let me know if that fixes the problem.

**Comment by omkartin** [comment]
@michaelkourlas  Wow that worked. Awesome. Thanks a lot.

Also it is printing: <?xml version='1.0'?>

How can I make it <?xml version="1.0" encoding="UTF-8"?> ?

**Comment by michaelkourlas** [comment]
You have to provide a format options object when calling toString(). See the docs for more details.

**Comment by omkartin** [comment]
@michaelkourlas  This worked
`var options = {
  declaration: {
    include: true,
    encoding: "UTF-8",
    version: "1.0"
  }
};`

`js2xmlparser.parse("Inventory", obj, options)`

Thanks a lot Michael
