### ISSUE TITLE
Text content in xml tags should not be indented

### ISSUE THREAD

**Issue by just-boris** [michaelkourlas/node-js2xmlparser#60]
The following code

```js
const js2xmlparser = require("js2xmlparser")
const obj = {
 content: `
multiline content
should not be indented
`
};

js2xmlparser.parse("test", obj);
```

Produces the following xml:

```xml
<?xml version='1.0'?>
<test>
    <content>
    multiline content
    should not be indented
    </content>
</test>
```

When I am parsing this back, the text content of the `content` tag gains extra indentation, which is not expected result. I expect to receive my string as it was initially formatted.

**Comment by DudaGod** [comment]
I've just looked to the documentation and that's what I found - http://www.kourlas.com/node-js2xmlparser/docs/3.0.0/interfaces/iformatoptions.html
It turns out that it's not a bug, because for default `pretty` option is - `undefined` and this means that it uses 4 spaces.

```
const js2xmlparser = require("js2xmlparser");
const obj = {
  content: `
multiline content
should not be indented
`
};

js2xmlparser.parse("test", obj, {format: {pretty: false}});
```

**Comment by just-boris** [comment]
@DudaGod your fix gives you the expected result, but it makes all XML unindented.

However, I am trying to show here, that XML formatter doesn't work correctly. Let's try to parse generated XML back, using [xml2js](https://github.com/Leonidas-from-XIV/node-xml2js)

```js
const USE_PRETTY = false; // try to change this flag

// all code as before
const js2xmlparser = require("js2xmlparser");
const {parseString: parseXml} = require('xml2js');
const obj = {
  content: `
multiline content
should not be indented
`
};
const xmlstr = js2xmlparser.parse("test", obj, {format: {pretty: USE_PRETTY}});

// parse generated output
parseXml(xmlstr, (err, res) => console.log(res.test.content))
```

You see different text in the console, depending from the value of `pretty` setting. This is not good, data structure should remain the same, regardless the pretty-printing setup.

**Comment by just-boris** [comment]
@michaelkourlas I have explored a possible way to fix it and come up with the solution, that you can recursively pass `depth` option into `toString` methods instead of indenting the whole child's content here: https://github.com/michaelkourlas/node-xmlcreate/blob/master/src/nodes/XmlElement.ts#L347

I expect this to fix the issue, but I can not provide a PR with that very soon. Sorry.

**Comment by michaelkourlas** [comment]
I'll add an option to configure this.

**Comment by michaelkourlas** [comment]
On second thought, I'm just not going to indent multi-line character data when pretty-printing. This behaviour is simply wrong, so I'm not going to bother making it configurable.
