### ISSUE TITLE
Characters not allowed in XML names

### ISSUE THREAD

**Issue by YuantongL** [michaelkourlas/node-js2xmlparser#61]
I've been trying to convert this JSON to XML

var obj = {
	"note": {
		"xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
		"xmlns:xs": "http://www.w3.org/2001/XMLSchema",
		"xsi:type": "xs:string",
		"$t": "$0.0/sqft"
	}
};

var js2xmlparser = require("js2xmlparser");
console.log("\nthis is the result");
console.log(js2xmlparser.parse("result", obj));

It says Error: name should not contain characters not allowed in XML names at XmlElement.set [as name]

I find out it's complaining about the "$" in the name "$t". Is there a way to get around this?

**Comment by michaelkourlas** [comment]
I think it might be a good idea to add support for an option that will substitute invalid XML characters with a placeholder character. This should fix your problem.

In the meantime, you can pre-process your object and remove the invalid characters yourself before passing it to js2xmlparser.

**Comment by paglias** [comment]
Is there a way to get the keys that are causing these errors? i'm having an hard time finding what's causing this problem

**Comment by xjtumalin** [comment]
Please try this:
console.log(js2xmlparser.parse("result", JSON.parse(JSON.stringify(obj))));

It works for me.

**Comment by michaelkourlas** [comment]
An option to substitute invalid XML characters with a placeholder character will be added in the next release.

In the same release, the error messages will provide some additional context to determine where problems are.

**Comment by appdevjrcigars** [comment]
Thanks @michaelkourlas 
A method to validate the json to xml would be really nice!

**Comment by benmarten** [comment]
I'm wondering why this even throws an error, since the $ sign is actually in quotes.

**Comment by michaelkourlas** [comment]
> 
> 
> I'm wondering why this even throws an error, since the $ sign is actually in quotes.

I'm not sure I follow. `$` cannot appear in XML names.
