### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by natan88** [michaelkourlas/node-js2xmlparser#62]
date fields should not be in the format 2016-11-07T12:00:00.000Z?

**Comment by michaelkourlas** [comment]
I'm not really clear on what you're asking. Dates are automatically converted to their string representation which is in RFC 3339 format.

If you want to change this you can use the `typeHandlers` property in the options object to change it to something else.

**Comment by natan88** [comment]
thanks for listening

**Comment by sators** [comment]
For those in the future looking for an example:

http://www.kourlas.com/node-js2xmlparser/docs/3.0.0/interfaces/ioptions.html#typehandlers
