### ISSUE TITLE
How do I change single quotes to double quotes of attributes?

### ISSUE THREAD

**Issue by lsslu** [michaelkourlas/node-js2xmlparser#63]

**Comment by michaelkourlas** [comment]
Use `{format: {doubleQuotes: false}}` as your options object when calling `parse`. See the documentation for more details.

**Comment by raugaral** [comment]
where is the documentation?!

**Comment by michaelkourlas** [comment]
It's linked to from the readme:

https://github.com/michaelkourlas/node-js2xmlparser#usage
