### ISSUE TITLE
missing encoding='UTF-8' in head

### ISSUE THREAD

**Issue by QplaX** [michaelkourlas/node-js2xmlparser#64]
When parsing an object to XML, the resulting first xml-line:

`<?xml version="1.0" ?>`

expected would be: 
`<?xml version="1.0" encoding="UTF-8"?>`

My call to js2xmlparser: 
`this.js2xmlparser.parse('rootName', xmlObj);`
  
What to do to add the encoding? 
Thanks in advance

**Comment by iliocatallo** [comment]
Hi,

Check the example file, it contains the [relevant option](https://github.com/michaelkourlas/node-js2xmlparser/blob/92f877117dc0beff56f22b39e3431b0f671873df/examples/example.js#L89) you are looking for.

**Comment by bajtos** [comment]
@QplaX I think this should fix the issue for you:

```js
this.js2xmlparser.parse('rootName', xmlObj, {declaration: {encoding: 'UTF-8'}});
```

@iliocatallo I am proposing to change the the default encoding value to be UTF-8, it will make migration from older version easier. What do you think?
