### ISSUE TITLE
Array of objects doesn't work as expected

### ISSUE THREAD

**Issue by RossD13** [michaelkourlas/node-js2xmlparser#67]
`var myObj = {name:"Ross", phones:[{phone: {no : "1223", type:"mobile"}}, {phone: {no : "666", type:"evil"}}]};
var xmlobj = js2xml.parse("person", myObj);

expect one element for phones, with each phone inside it 
phones
   phone
   phone
/phones

instead, I get repeated element phones
phones
   phone
/phones
phones
   phone
/phones

**Comment by othierry** [comment]
up ?

**Comment by othierry** [comment]
@RossD13  https://github.com/michaelkourlas/node-js2xmlparser/issues/51
