### ISSUE TITLE
Generate xml without the root element

### ISSUE THREAD

**Issue by jpaaso** [michaelkourlas/node-js2xmlparser#69]
Hi,

Is there a way to generate xml without the root element:

```js
console.log(js2xmlparser.parse(/* <no root> ,*/ { foo: 1, bar: 2}));
```
-->
```xml
<foo>1</foo>
<bar>2</bar>
```

Thanks!

**Comment by daveferrara1** [comment]
Needing this too.

**Comment by gorillamoe** [comment]
As a work-around I use this:

```javascript
xml = js2xmlparser
        .parse("super:evil", json)
        .split("\n");
xml.splice(1, 1);
xml.splice(-1, 1);
console.log(xml.join("\n"));
```

**Comment by michaelkourlas** [comment]
Can't you just iterate through your object, call `parse` on each key/value pair, and concatenate the results?

I don't think it's a good idea to make it easier to generate invalid XML.
