### ISSUE TITLE
Not Escaping ">" In String Between Tags

### ISSUE THREAD

**Issue by ziplokk1** [michaelkourlas/node-js2xmlparser#74]
This is kind of a stupid edge case, but I need to have an XML string within an XML tag.

Example of what I need:

```xml
<Root>
  <Element>&lt;SubElement attr="abc"/&gt;</Element>
</Root>
```

Example of what is output:

```xml
<Root>
  <Element>&lt;SubElement attr="abc"/></Element>
</Root>
```

Is this a bug, or am I just doing something wrong here (other than the obvious XML within XML)?

**Comment by ziplokk1** [comment]
If I create my XML string and then do:

```javascript
const subelement = '<SubElement attr="abc">'.replace(/\>/g, '&lt;');
const xml = js2xmlparser.parse({Root: {Element: subelement}});
console.log(xml);
```

it outputs `'<?xml version=\'1.0\'?>\n<Root>\n    <Element>&lt;SubElement attr="abc"&amp;lt;</Element>\n</Root>'`

So I cant just replace the '>' because it encodes the ampersand as `&amp;`

**Comment by ziplokk1** [comment]
It looks like this is an issue with the xmlcreate repo. I will open an issue there.

**Comment by michaelkourlas** [comment]
I've responded in the other issue you opened.
