### ISSUE TITLE
XML contains single quote

### ISSUE THREAD

**Issue by gauravpp** [michaelkourlas/node-js2xmlparser#75]
Hi, When I am converting from json to XML I am getting single quote for attribute. is there any fix available for this?

Json : 

{
    "firstName": "John",
    "lastName": "Smith",
    "dateOfBirth": new Date(1964, 7, 26),
    "address": {
        "@": {
            "type": "home",
            "gg": "123"
        },
        "streetAddress": "3212 22nd St",
        "city": "Chicago",
        "state": "Illinois",
        "zip": 10000
    },
    "phone": [
        {
            "@": {
                "type": "home"
            },
            "#": "123-555-4567"
        },
        {
            "@": {
                "type": "cell"
            },
            "#": "890-555-1234"
        },
        {
            "@": {
                "type": "work"
            },
            "#": "567-555-8901"
        }
    ],
    "email": "john@smith.com"
}

XML:

<?xml version='1.0'?>
<person>
    <firstName>John</firstName>
    <lastName>Smith</lastName>
    <dateOfBirth>Wed Aug 26 1964 00:00:00 GMT+0530 (India Standard Time)</dateOfBirth>
    <address type='home' gg='123'>
        <streetAddress>3212 22nd St</streetAddress>
        <city>Chicago</city>
        <state>Illinois</state>
        <zip>10000</zip>
    </address>
    <phone type='home'>123-555-4567</phone>
    <phone type='cell'>890-555-1234</phone>
    <phone type='work'>567-555-8901</phone>
    <email>john@smith.com</email>
</person>

**Comment by michaelkourlas** [comment]
Yes -- add `doubleQuotes: true` to the options object that you pass to your invocation of the `parse` method.

**Comment by notchris** [comment]
I'm having a similar issue, am I passing the option correctly?

`const test = js2xmlparser.parse("test", data, {
    doubleQuotes: true,
    declaration: {
        encoding: "UTF-8"
    }
})`

Thanks, great library!
