### ISSUE TITLE
Colons in JSON keys

### ISSUE THREAD

**Issue by ccnixon** [michaelkourlas/node-js2xmlparser#76]
Hi, thanks so much for your work here!

I've run into an issue when passing in JSON objects that may contain keys with colons. For example, a JSON value might look like this:

```
{ "foo:bar": true }
```
And the resulting XML looks like this:
```
<?xml version="1.0" encoding="UTF-8"?><request><foo:bar>true</foo:bar></request>
```
This is invalid XML as a Namespace for `foo` has not been defined. Here's the specific error when passed through a validator:

```
The prefix "foo" for element "foo:bar" is not bound.
```

Is there a way to escape or replace specific characters in keys, specifically colons?

Thanks again!

**Comment by michaelkourlas** [comment]
No -- you'll either have to define a namespace or preprocess the object to remove the colons from the object keys.
