### ISSUE TITLE
typeHandlers [object Boolean] doesn't work in 4.0.0

### ISSUE THREAD

**Issue by darksabrefr** [michaelkourlas/node-js2xmlparser#80]
Hello,

Previously in 3.0.0, using a type handler for boolean field does correct things, it was transforming booleans into what you want.
But it seems that, in some cases with 4.0.0, the booleans are stringified, so the type handler for them is not triggered.

**Comment by michaelkourlas** [comment]
Can you provide an example?

**Comment by michaelkourlas** [comment]
I'm going to close this for now, but if you provide an example I'll re-open the issue.
