### ISSUE TITLE
add nil="true" to keys whose values are empty string or undefined

### ISSUE THREAD

**Issue by Kaliph** [michaelkourlas/node-js2xmlparser#86]
I would like to add nil="true" to keys whose values are an empty string or undefined

if my json looks like this:

`let json = {
      key: ""
}`

or 

`let json = {
      key: undefined
}`

The xml output should be like this

`<key nil="true"/>`

Is this somehow possible? I only found the example for the root element. Thankyou

**Comment by Kaliph** [comment]
I found the part in xmlcreate library where to edit the closing tag.

`if (childStr.length === 0 && this._useSelfClosingTagIfEmpty) {
   // Element empty tag end
       str += ' nil="true"/>';
 }`

 It would be great to have this as an option in the library to select a custom closing tag when strings are empty.

**Comment by michaelkourlas** [comment]
Unfortunately, I think too few people would use this option to justify adding it.

My suggestion would be to pre-process your JSON to replace `{key: ""}` with `{key: {"@": {nil: "true"}}}`, which I think should do what you want.
