### ISSUE TITLE
New line not exptected with CDATA

### ISSUE THREAD

**Issue by gsaraceno92** [michaelkourlas/node-js2xmlparser#93]
## Use case
Use js2xmlparser to parse xml string and set cdatakeys as follow :
```javascript
parse(
...,
{ cdataKeys: ['*']},
...
)
```
--- 
### Expected result
A parsed xml as follow:
```xml
...
<interiors_color><![CDATA[Nero]]></interiors_color>
...
```

### Actual result
```xml
...
<interiors_color>
    <![CDATA[Nero]]>
</interiors_color>
...
```

### **Issue**
The package set newline in the xml tag; this is an unwanted behaviour since the value is not read as the original.

**Comment by michaelkourlas** [comment]
Pretty-printing is enabled by default; it sounds like you want to disable it.
