### ISSUE TITLE
Add Namespace in the root element using js2XmlParser

### ISSUE THREAD

**Issue by savanth200** [michaelkourlas/node-js2xmlparser#95]
Hi Team, 

Using js2xml parser, we are converting our json to xml. And we had a scenario in which in the converted xml root element should need a namespace with the url configured. Am adding my code below and please respond us if it could have a solution for this. It would really help. 

//FileType = "RootName"
  public convertToXML(formObject,fileType) {
      let options = {
                    format: {
                      doubleQuotes: true
                    },
                    declaration: {
                      include: true,
                      encoding :"utf-8"
                    }
                   }
      var result = this.removeNullOrEmptyObjects(formObject);
      var jsonObj= pascalizeKeys(result);
      console.log(result);
      var file = new Blob([JsonToXML.parse(fileType, jsonObj,options)], {type: 'application/xml'});

**Current output:** 

![image](https://user-images.githubusercontent.com/10268565/149269766-e43f69ec-b615-43db-8eab-245d20c2ff2b.png)

**We expecting an output with root element like this :** 

![image](https://user-images.githubusercontent.com/10268565/149269797-6b6f6630-1e77-40f6-af77-183e1a56e957.png)

**Comment by michaelkourlas** [comment]
Please see the example in the README.
