### ISSUE TITLE
How to add comments to XML?

### ISSUE THREAD

**Issue by michaelmrn** [michaelkourlas/node-js2xmlparser#98]
Hey, nice library! - is there a way to add comments e.g. `<!-- -->` within the XML tags for example:
`<rss version="2.0" ><!--MY COMMENT HERE--> </rss>`

**Comment by michaelkourlas** [comment]
No -- this library isn't really built for that. Consider using [xmlcreate](https://github.com/michaelkourlas/node-xmlcreate) instead.
