### ISSUE TITLE
[Question] Process values during conversion.

### ISSUE THREAD

**Issue by armoucar** [michaelkourlas/node-js2xmlparser#99]
Hi, I was able to process values for Dates using the `typeHandlers` option. But I have a specific case where I have to format a number to have an exact amount of characters:

```json
{
  "myNumber": 7
}
```

```xml
<myNumber>007<myNumber>
```

Is there anyway I could achieve that but specifically targeting the `myNumber` prop without triggering the same behavior to other number fields? Thanks

**Comment by michaelkourlas** [comment]
No, this isn't possible. It should be simple enough to preprocess the JSON to replace the number with an appropriate string, though.
